name: Generate Snake ğŸ

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug info
        run: |
          git --version
          git config --list

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: Marcelo844
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: List output
        run: ls -la dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github-snake
          path: dist/github-snake.svg
